#!/bin/sh
# Name: checksize
# Project: AVR-USB
# Author: Christian Starkjohann
# Creation Date: 2004-12-29
# Tabsize: 4
# Copyright: (c) 2005 OBJECTIVE DEVELOPMENT Software GmbH.
# Revision: $Id: checksize 110 2006-02-07 21:26:09Z cs $
#
# This file has been copied from HIDKeys.2007-03-29.tar.gz


if [ -z "$1" ]; then
	echo "Usage: ./checksize filename.elf"
	exit
elif [ ! -f "$1" ]; then
	echo "File '$1' was not found"
	exit
fi


# ATmega8 has 8K of flash and 1K of RAM
codelimit=8192
datalimit=960   # leave 64 bytes for stack

error=0

if [ $# -gt 1 ]; then
	codelimit="$2"
fi
if [ $# -gt 2 ]; then
	datalimit="$3"
fi

# Sample avr-size output:
#   text    data     bss     dec     hex filename
#   2614      22      75    2711     a97 main.elf
#
# The total amount of data to Flash ROM is text+data.
# The total amount of RAM is data+bss.
#
# Note: the EEPROM seems to get incorrectly counted into the data section.
#
#
# See also: http://www.nongnu.org/avr-libc/user-manual/mem_sections.html

set -- `avr-size -d "$1" | awk '/[0-9]/ {print $1 + $2, $2 + $3, $2}'`
if [ "$1" -gt $codelimit ]; then
	echo "*** code size $1 exceeds limit of $codelimit"
	error=1
else
	echo "ROM: $1 bytes (data=$3) / max=$codelimit"
fi
if [ "$2" -gt $datalimit ]; then
	echo "*** data size $2 exceeds limit of $datalimit"
	error=1
else
	echo "RAM: $2 bytes / max=$datalimit"
fi

exit $error
